/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ci;

public class App {

    public static void main(String[] args) {
        System.out.println("Hello, world!");
    }
}
